// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRmUIPRpdNU2Q5PWb2JIK7w1r1ejEIQUI',
    appId: '1:837624027822:web:74c87a0d853008f7f46b3f',
    messagingSenderId: '837624027822',
    projectId: 'veksis-ogrenci-db',
    authDomain: 'veksis-ogrenci-db.firebaseapp.com',
    storageBucket: 'veksis-ogrenci-db.appspot.com',
    measurementId: 'G-L8EY7QL4JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDErsHGNHZmkRDkJrzR3wWP-rY2h9DwqMI',
    appId: '1:837624027822:android:091285d46c433bedf46b3f',
    messagingSenderId: '837624027822',
    projectId: 'veksis-ogrenci-db',
    storageBucket: 'veksis-ogrenci-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzKFPNA5BYwrudeni96biH_USuyRAzka8',
    appId: '1:837624027822:ios:ff9c400191dd696ff46b3f',
    messagingSenderId: '837624027822',
    projectId: 'veksis-ogrenci-db',
    storageBucket: 'veksis-ogrenci-db.appspot.com',
    iosBundleId: 'com.example.veksisOgrenciApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzKFPNA5BYwrudeni96biH_USuyRAzka8',
    appId: '1:837624027822:ios:ff9c400191dd696ff46b3f',
    messagingSenderId: '837624027822',
    projectId: 'veksis-ogrenci-db',
    storageBucket: 'veksis-ogrenci-db.appspot.com',
    iosBundleId: 'com.example.veksisOgrenciApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRmUIPRpdNU2Q5PWb2JIK7w1r1ejEIQUI',
    appId: '1:837624027822:web:522f6d82a3617349f46b3f',
    messagingSenderId: '837624027822',
    projectId: 'veksis-ogrenci-db',
    authDomain: 'veksis-ogrenci-db.firebaseapp.com',
    storageBucket: 'veksis-ogrenci-db.appspot.com',
    measurementId: 'G-06LZPQP2GP',
  );
}
